services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /application
        restart: unless-stopped
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=questions
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        ports:
            - '2003:3306'
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 10s
            timeout: 5s
            retries: 5

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        restart: unless-stopped
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '2001:80'

    php-fpm:
        build: phpdocker/php-fpm
        restart: unless-stopped
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/fpm/conf.d/99-overrides.ini'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/cli/conf.d/99-overrides.ini'

#    grafana:
#        image: grafana/grafana:latest
#        container_name: grafana
#        restart: unless-stopped
#        environment:
#            - GF_SECURITY_ADMIN_PASSWORD=admin
#            - GF_SECURITY_ADMIN_USER=admin
#        ports:
#            - "2004:3000"
#        volumes:
#            - grafana_data:/var/lib/grafana
#            - ./phpdocker/grafana/provisioning:/etc/grafana/provisioning
#            - ./phpdocker/grafana/dashboards:/var/lib/grafana/dashboards
#        depends_on:
#            - mysql


    mailhog:
        image: mailhog/mailhog
        container_name: mailhog
        restart: always
        environment:
            MH_AUTH_FILE: /mailhog.auth
            MH_MAILDIR_PATH: /data
            MH_STORAGE: maildir
        volumes:
            - ./mailhog.auth:/mailhog.auth:ro
            - ./data:/data:rw
        ports:
            - "1025:1025" #127.0.0.1:1025:1025
            - "8025:8025"
volumes:
    grafana_data:

networks:
    default:
        external: true
        name: questions
