question_controllers:
    resource:
        path: ../src/Question/Controller/
        namespace: App\Question\Controller
    type: attribute
question_admin_controllers:
    resource:
        path: ../src/Question/Controller/Admin/
        namespace: App\Question\Controller\Admin
    type: attribute
security_controllers:
    resource:
        path: ../src/User/UserInterface/Controller/
        namespace: App\User\UserInterface\Controller
    type: attribute
organization_controllers:
    resource:
        path: ../src/Organization/Presentation/Controller/
        namespace: App\Organization\Presentation\Controller
    type: attribute
api_login_check:
    path: /api/login_check
healthCheckController:
    resource:
        path: ..src/HealthCheck/UserInterface/Controller
        namespace: App\User\UserInterface\Controller
